"""init

Revision ID: 7356bc3a04af
Revises: bcc714072d0a
Create Date: 2026-03-31 07:32:56.257728
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision = '7356bc3a04af'
down_revision = 'bcc714072d0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('follower_id', table_name='follows')
    op.drop_index('ix_follows_followee_id', table_name='follows')
    op.drop_index('ix_follows_follower_id', table_name='follows')
    op.drop_index('ix_follows_id', table_name='follows')
    op.drop_table('follows')
    op.drop_index('ix_messages_id', table_name='messages')
    op.drop_index('ix_messages_receiver_id', table_name='messages')
    op.drop_index('ix_messages_sender_id', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_activities_id', table_name='activities')
    op.drop_table('activities')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('activity_id', table_name='activity_registrations')
    op.drop_index('ix_activity_registrations_activity_id', table_name='activity_registrations')
    op.drop_index('ix_activity_registrations_id', table_name='activity_registrations')
    op.drop_table('activity_registrations')
    op.drop_index('ix_comments_article_id', table_name='comments')
    op.drop_index('ix_comments_id', table_name='comments')
    op.drop_table('comments')
    op.alter_column('articles', 'content',
               existing_type=mysql.LONGTEXT(),
               type_=sa.Text(length=16777215),
               existing_nullable=False)
    op.add_column('users', sa.Column('csdn_url', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'csdn_url')
    op.alter_column('articles', 'content',
               existing_type=sa.Text(length=16777215),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.create_table('comments',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('article_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='comments_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name='comments_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_comments_id', 'comments', ['id'], unique=False)
    op.create_index('ix_comments_article_id', 'comments', ['article_id'], unique=False)
    op.create_table('activity_registrations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('activity_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_identifier', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('nickname', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('checked_in', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('registered_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], name='activity_registrations_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_activity_registrations_id', 'activity_registrations', ['id'], unique=False)
    op.create_index('ix_activity_registrations_activity_id', 'activity_registrations', ['activity_id'], unique=False)
    op.create_index('activity_id', 'activity_registrations', ['activity_id', 'user_identifier'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('username', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('action', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('resource', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('resource_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('detail', mysql.TEXT(), nullable=True),
    sa.Column('ip_address', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('user_agent', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_audit_logs_user_id', 'audit_logs', ['user_id'], unique=False)
    op.create_index('ix_audit_logs_id', 'audit_logs', ['id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('activities',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('organizer', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('start_time', mysql.DATETIME(), nullable=False),
    sa.Column('end_time', mysql.DATETIME(), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('max_seats', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_activities_id', 'activities', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('receiver_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.TEXT(), nullable=False),
    sa.Column('is_read', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name='messages_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name='messages_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_messages_sender_id', 'messages', ['sender_id'], unique=False)
    op.create_index('ix_messages_receiver_id', 'messages', ['receiver_id'], unique=False)
    op.create_index('ix_messages_id', 'messages', ['id'], unique=False)
    op.create_table('follows',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('follower_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('followee_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], name='follows_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], name='follows_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_follows_id', 'follows', ['id'], unique=False)
    op.create_index('ix_follows_follower_id', 'follows', ['follower_id'], unique=False)
    op.create_index('ix_follows_followee_id', 'follows', ['followee_id'], unique=False)
    op.create_index('follower_id', 'follows', ['follower_id', 'followee_id'], unique=True)
    # ### end Alembic commands ###
